name: ci

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#      - name: Log in to registry
#        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      # cache 'upstream' and 'demo/node_modules' folders
      - uses: actions/cache@v2
        with:
          path: | 
            upstream
            demo/node_modules
          key: ${{ runner.os }}-upstream-${{ hashFiles('**/upstream/llvm-project/llvm/VERSION.txt') }}
          restore-keys: ${{ runner.os }}-upstream-

      - name: Build
        run: |
          ./build-with-docker.sh

      # install node 14
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Build demo
        run: |
          ./build-demo.sh

      - name: GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          build_dir: build/demo/

#      - uses: actions/upload-artifact@v3
#        with:
#          name: dist
#          path: |
#            ./build/llvm/bin/llvm-box.wasm
#            ./build/llvm/bin/llvm-box.mjs
#          retention-days: 7


#  release:
#    needs: build
#    name: Create Release
#    runs-on: ubuntu-latest
#    if: startsWith(github.ref, 'refs/tags/')
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/download-artifact@v3
#      - uses: softprops/action-gh-release@v1
#        with:
#          files: dist/*.*
#      - name: Setup npmrc
#        run: |
#          echo "@jprendes:registry=https://npm.pkg.github.com/" >> .npmrc
#          echo "//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}" >> .npmrc
#      - name: Publish
#        run: npm publish
